openapi: 3.0.1
info:
  title: NanoQSAR Webservices
  version: 0.0.1
servers:
- url: https://atena.urv.cat/model/api/
paths:
  /puzyn_2011:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PuzynMessage'
      responses:
        200:
          description: OK

components:
  schemas:
    PuzynMessage:
      type: object
      properties:
        gasCation:
          type: number
          description: Enthalpy of formation of a gaseous cation (Kcal/mol)
      required:
        - gasCation
